#!/bin/bash
DATE=$(date +%Y-%m-%d)
echo "=== 社長レビュー: $DATE 13:00 ==="
echo ""
echo "■ Note記事（要確認・Noteに投稿）"
ls -la employees/logs/note-articles/note-${DATE}-*.md 2>/dev/null || echo "  まだ完成していません"
echo ""
echo "■ リプ案（選んで実行）"
cat employees/logs/reply-drafts-${DATE}.md 2>/dev/null | head -50 || echo "  未作成"
echo ""
echo "■ いいねプラン（確認してGO）"
cat employees/logs/like-plan-${DATE}.md 2>/dev/null | head -30 || echo "  未作成"
echo ""
echo "■ 引用ポスト案（1件選んで投稿）"
cat employees/logs/quote-drafts-${DATE}.md 2>/dev/null | head -50 || echo "  未作成"
echo ""
echo "■ 朝・昼ポスト（自動投稿済み・事後確認）"
cat employees/logs/posts-${DATE}.md 2>/dev/null | head -30 || echo "  未作成"
echo ""
echo "■ 新規目論見書の取得状況"
ls -la employees/data/prospectus/*.pdf 2>/dev/null | tail -5 || echo "  新規取得なし"
